name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 8 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1.0
      with:
        repository: nicholasdille/buildkit
        tags: rootless
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        add_git_labels: true
        always_pull: true
        
